touch 1-1.md 1-2.md 1-3.md 1-4.md 1-5.md 1-6.md 1-7.md 1-8.md 1-9.md 2-1.md 2-2.md 2-3.md 2-4.md 2-5.md 2-6.md 2-7.md 2-8.md 2-9.md 3-1.md 3-2.md 3-3.md 3-4.md 3-5.md 3-6.md 3-7.md 3-8.md 3-9.md 4-1.md 4-2.md 4-3.md 4-4.md 4-5.md 4-6.md 4-7.md 4-8.md 4-9.md

echo # 使用load()方法异步请求数据 >> 1-1.md
echo # 使用getJSON()方法异步加载JSON格式数据 >> 1-2.md
echo # 使用getScript()方法异步加载并执行js文件 >> 1-3.md
echo # 使用get()方法以GET方式从服务器获取数据 >> 1-4.md
echo # 使用post()方法以POST方式从服务器发送数据 >> 1-5.md
echo # 使用serialize()方法序列化表单元素值 >> 1-6.md
echo # 使用ajax()方法加载服务器数据 >> 1-7.md
echo # 使用ajaxSetup()方法设置全局Ajax默认选项 >> 1-8.md
echo # 使用ajaxStart()和ajaxStop()方法 >> 1-9.md
echo # 表单验证插件——validate >> 2-1.md
echo # 表单插件——form >> 2-2.md
echo # 图片灯箱插件——lightBox >> 2-3.md
echo # 图片放大镜插件——jqzoom >> 2-4.md
echo # cookie插件——cookie >> 2-5.md
echo # 搜索插件——autocomplete >> 2-6.md
echo # 右键菜单插件——contextmenu >> 2-7.md
echo # 自定义对象级插件——lifocuscolor插件 >> 2-8.md
echo # 自定义类级别插件——twoaddresult >> 2-9.md
echo # 拖曳插件——draggable >> 3-1.md
echo # 放置插件——droppable >> 3-2.md
echo # 拖曳排序插件——sortable >> 3-3.md
echo # 面板折叠插件——accordion >> 3-4.md
echo # 选项卡插件——tabs >> 3-5.md
echo # 对话框插件——dialog >> 3-6.md
echo # 菜单工具插件——menu >> 3-7.md
echo # 微调按钮插件——spinner >> 3-8.md
echo # 工具提示插件——tooltip >> 3-9.md
echo # 获取浏览器的名称与版本信息 >> 4-1.md
echo # 检测浏览器是否属于W3C盒子模型 >> 4-2.md
echo # 检测对象是否为空 >> 4-3.md
echo # 检测对象是否为原始对象 >> 4-4.md
echo # 检测两个节点的包含关系 >> 4-5.md
echo # 字符串操作函数 >> 4-6.md
echo # URL操作函数 >> 4-7.md
echo # 使用$.extend()扩展工具函数 >> 4-8.md
echo # 使用$.extend()扩展Object对象 >> 4-9.md